# Generated by Django 4.1.7 on 2023-02-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
