# Generated by Django 4.1.7 on 2023-02-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_electronics_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
