# Generated by Django 4.1.7 on 2023-03-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_alter_electronics_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
