# Generated by Django 4.1.7 on 2023-03-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_alter_electronics_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='details',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
