# Generated by Django 4.1.7 on 2023-03-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_electronics_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='details',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
