# Generated by Django 4.1.7 on 2023-03-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='image1',
            field=models.ImageField(default='abc.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='electronics',
            name='image2',
            field=models.ImageField(default='abc.jpg', upload_to='images'),
        ),
    ]
