# Generated by Django 4.1.7 on 2023-03-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_alter_electronics_price'),
        ('UserApp', '0002_remove_userinfo_id_alter_userinfo_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('electronics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.electronics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.userinfo')),
            ],
        ),
    ]
