# Generated by Django 4.1.7 on 2023-03-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_mycart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mycart',
            table='MyCart',
        ),
    ]
