# Generated by Django 4.1.7 on 2023-03-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_ordermaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default='06, Vivekanand Nagar Bhadgaon Road, Pachora', max_length=300),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mobile_no',
            field=models.CharField(default=8459707078, max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
