# Generated by Django 4.1.7 on 2023-03-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_userinfo_address_userinfo_mobile_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='order_id',
            field=models.CharField(default=98193, max_length=5),
        ),
    ]
