# Generated by Django 4.1.7 on 2023-03-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_userinfo_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='order_id',
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='order_id',
            field=models.CharField(default=29700, max_length=5),
        ),
    ]
