# Generated by Django 4.1.7 on 2023-03-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_remove_userinfo_order_id_ordermaster_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='order_id',
            field=models.CharField(default=80244, max_length=5),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
