# Generated by Django 4.1.7 on 2023-03-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_alter_ordermaster_order_id_alter_userinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='order_id',
            field=models.CharField(default=19121, max_length=5),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
