# Generated by Django 4.1.7 on 2023-03-20 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_alter_ordermaster_order_id_alter_userinfo_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='arrival',
            field=models.DateField(default=datetime.date(2023, 3, 23)),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='order_id',
            field=models.CharField(default=470486, max_length=5),
        ),
    ]
