# Generated by Django 4.1.7 on 2023-03-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_ordermaster_arrival_alter_ordermaster_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='qty',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='order_id',
            field=models.CharField(default=828822, max_length=5),
        ),
    ]
