# Generated by Django 4.1.7 on 2023-03-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_ordermaster_qty_alter_ordermaster_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='orderStatus',
            field=models.CharField(default='Preparing for dipatch', max_length=25),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='order_id',
            field=models.CharField(default=948924, max_length=5),
        ),
    ]
