# Generated by Django 4.1.7 on 2023-03-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_ordermaster_orderstatus_alter_ordermaster_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='order_id',
            field=models.CharField(default=162292, max_length=5),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='qty',
            field=models.CharField(max_length=2),
        ),
    ]
