# Generated by Django 4.1.7 on 2023-03-27 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_alter_ordermaster_arrival_alter_ordermaster_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='arrival',
            field=models.DateField(default=datetime.date(2023, 3, 30)),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='order_id',
            field=models.CharField(max_length=6),
        ),
    ]
