# Generated by Django 4.1.7 on 2023-03-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_userinfo_email_alter_ordermaster_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=15),
        ),
    ]
