# Generated by Django 4.1.7 on 2023-03-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_alter_userinfo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='zip_code',
            field=models.CharField(default='424201, Maharashtra', max_length=20),
        ),
    ]
