# Generated by Django 4.1.7 on 2023-03-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0019_remove_userinfo_password_userinfo_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
    ]
