# Generated by Django 4.1.6 on 2024-07-16 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0023_alter_userinfo_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermaster",
            name="arrival",
            field=models.DateField(default=datetime.date(2024, 7, 19)),
        ),
    ]
