# Generated by Django 4.1.6 on 2024-08-08 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0024_alter_ordermaster_arrival"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermaster",
            name="arrival",
            field=models.DateField(default=datetime.date(2024, 8, 11)),
        ),
    ]
