# Generated by Django 5.2.11 on 2026-02-05 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0025_alter_ordermaster_arrival"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermaster",
            name="arrival",
            field=models.DateField(default=datetime.date(2026, 2, 8)),
        ),
    ]
